from dotenv import load_dotenv
import os
load_dotenv()

class Config:
    SECRET_KEY = os.getenv('SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
    SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS')
    SECURITY_PASSWORD_HASH = os.getenv("SECURITY_PASSWORD_HASH")
    SECURITY_PASSWORD_SALT = os.getenv("SECURITY_PASSWORD_SALT")
    SECURITY_JOIN_USER_ROLES = os.getenv("SECURITY_JOIN_USER_ROLES")
    SECURITY_TOKEN_AUTHENTICATION_HEADER = os.getenv("SECURITY_TOKEN_AUTHENTICATION_HEADER")
    CACHE_TYPE = os.getenv("CACHE_TYPE")
    CACHE_REDIS_HOST = os.getenv("CACHE_REDIS_HOST")
    CACHE_REDIS_DB = os.getenv("CACHE_REDIS_DB")
    MAIL_SERVER = 'localhost'
    MAIL_PORT = 1025
    MAIL_DEFAULT_SENDER ='no-reply@CreativeMerge.com'